### ISSUE TITLE
Lucee 5.0

### ISSUE THREAD

**Issue by indynz** [boughtonp/lucee-on-jetty#1]
Hi

Thanks for your effort. Just wanted to check if you have Lucee 5.0 on the roadmap.

Thanks

Indy

**Comment by we3geeks** [comment]
+1 Would very much like to see an update covering Lucee 5

**Comment by boughtonp** [comment]
Yep, Lucee 5 support will happen.

There's a compatibility issue I'd started looking into before _stuff_ happened, but I'll be back on it soon, and once that issue is resolved I'll get everything updated.

**Comment by boughtonp** [comment]
Issue solved with [v0.6](https://github.com/boughtonp/lucee-on-jetty/releases) release.
