### ISSUE TITLE
Documentation refers to override descriptor moved from ROOT.xml in latest commit.

### ISSUE THREAD

**Issue by dhartvigsenAmerisave** [boughtonp/lucee-on-jetty#2]
Because the latest commit removes the Override descriptor from the ROOT.xml file, the documentation should include how to enable the lucee servlet in each context in the webapps folder so session information can shared between the CFML servlet and other contexts.

**Comment by boughtonp** [comment]
> how to enable the lucee servlet in each context in the webapps folder

This is now already the case - the overrideDescriptor has moved to `lucee-webapp-common.xml`
which is applied globally via `lucee-global-webapp-common.xml` so it doesn't need to be added manually.

(If only some contexts should enable Lucee, the reference to `lucee-global-webapp-common.xml`
in `lucee-base/modules/lucee.mod` can be commented out and the overrideDescriptor line manually included as before.)

Didn't realise I hadn't updated the docs when I refactored out the module, so I'll get that done soon.



> so session information can shared between the CFML servlet and other contexts.

Not clear on what you're saying here?

The overrideDescriptor simply applies lucee-servlets.xml - the change to where it is has no reason to affect sessions.

**Comment by dhartvigsenAmerisave** [comment]
Thanks, for the update.   The second item is dealing with a difficulty I raised on the Lucee dev fourm itself, dealing with Lucee being able to pick up classes in a servlet's WEB-INF/classes folder for compiled classes specific to the web context I am trying to load. It appears that the ability to load compiled classes with their custom java class loader is not something they want to do with Lucee 5 See here: https://luceeserver.atlassian.net/browse/LDEV-315?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true. It's true that saying "session" is pretty nebulous at best. It had appeared that the servlet that loaded with it's classes wasn't able to be seen by the "Web session" started by Lucee, and I was getting null pointer and class not found exceptions when trying to load the classes that I needed Lucee to integrate with. (I was upgrading from Railo 2 all the way to Lucee 5).  My apologies.

**Comment by boughtonp** [comment]
This should be covered by latest documentation - please re-open if you feel anything needs clarifying.
